

# This file was *autogenerated* from the file find_ldlc_qubits.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import numpy as np 
import os
from fnmatch import fnmatch
from sage.matrix.symplectic_basis import symplectic_basis_over_ZZ


#files = os.listdir("ldlc_gens")
#files = ["gkpldlc_15_3_A.npy"]
files = os.listdir("ldlc_gens/large")
for f in files:
    if fnmatch(f,'*_A.npy'):
        print(f)
        #canonical_M_name = "ldlc_gens/"+f.replace("_A", "_canonical_M")
        canonical_M_name = "ldlc_gens/large/"+f.replace("_A", "_canonical_M")

        print(canonical_M_name)
        
        A = matrix(ZZ,np.load("ldlc_gens/large/"+f))
        F, C = symplectic_basis_over_ZZ(A)
        #print("F", F)
        #print("C", C)
        n = A.nrows()//_sage_const_2 
        #print(np.array(F))
        D=F[_sage_const_0 :n,n:]

        #print(F[0:n,n:])
        #print(F[n:,0:n])

        print(D.is_diagonal())
        loc_dims = set(np.array(D).diagonal())
        print(loc_dims)


        if _sage_const_2  in loc_dims:
            print("qubit found in : ", canonical_M_name)
            with open("ldlc_gens/large/qubit_containing.txt", "a") as file:
                # Write the string to the file, followed by a newline character
                file.write(canonical_M_name + "\n")

        #np.save(canonical_M_name, Cnp)
        #np.savetxt(canonical_M_name, Cnp)
        #serial_C = [str(c) for c in C]
        #print(serial_C)
        #print(len(serial_C[1]))
        #open(canonical_M_name+'.txt', 'w').write(str(C)) # write matrix A to text file
        #open(canonical_M_name+'.txt', 'w').write(serial_C) # write matrix A to text file

        # Open a text file for writing
        with open(canonical_M_name+'.txt', 'w') as f:
            # Iterate over the rows of the matrix
            for row in C.rows():
                # Write each row to the file, separating entries with spaces
                f.write(' '.join(str(entry) for entry in row) + '\n')

